#!/bin/bash -x

BASE_COLLECTION_PATH="/must-gather"


for i in $(/usr/bin/oc get virtualmachines --all-namespaces --no-headers | awk '{print $1}')
do
  resources+=("$i")
done

for resource in "${resources[@]}"; do
  for vm in $(/usr/bin/oc get virtualmachine -n "$resource" --no-headers |  awk -F ' ' '{print $1}'); do
    vm_path="${BASE_COLLECTION_PATH}/namespaces/${resource}/kubevirt.io/virtualmachines"

    if [[ $(/usr/bin/oc get virtualmachine "$vm" -o json -n "$resource" | grep -c "vm.kubevirt.io/template") -gt 0 ]]; then
      vm_path="$vm_path/template-based"
    else
      vm_path="$vm_path/custom"
    fi
    mkdir -p "${vm_path}"

    /usr/bin/oc get virtualmachine "$vm" -o yaml -n "$resource" > "$vm_path/$vm.yaml"
  done
done

exit 0
