#!/bin/bash -x

DIR_NAME=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${DIR_NAME}/common.sh"
check_command
get_log_collection_args

namespaces=()
# KubeVirt HCO related namespaces
namespaces+=("${INSTALLATION_NAMESPACE}" openshift-operator-lifecycle-manager openshift-marketplace)

# KubeVirt network related namespaces
NETWORK_TYPE=$(oc get network.config.openshift.io -o=jsonpath='{.items[0].spec.networkType}' | tr '[:upper:]' '[:lower:]')
if [[ "${NETWORK_TYPE}" == "ovnkubernetes" ]]; then
  namespaces+=(openshift-ovn-kubernetes)
elif [[ "${NETWORK_TYPE}" == "openshiftsdn" ]]; then
  namespaces+=(openshift-sdn)
fi

# Golden images namesapce
namespaces+=(openshift-virtualization-os-images)

# CDI
resources+=(cdi)

# Run the collection of namespaces using must-gather
echo "${namespaces[@]}" | tr ' ' '\n' | xargs -t -I{} -P "${PROS}" --max-args=1 sh -c 'echo inspecting namespace $1 && oc adm inspect ${log_collection_args} --dest-dir "${BASE_COLLECTION_PATH}" namespace $1' -- {}
