#!/bin/bash

IFS=$'\n'

BASE_COLLECTION_PATH="/must-gather"

NAMESPACE_PATH=${BASE_COLLECTION_PATH}/namespaces
NS=openshift-cnv

mkdir -p ${NAMESPACE_PATH}/${NS}

for name in $(oc get packagemanifest -n $NS -o=custom-columns=NAME:.metadata.name --no-headers)
do
    oc get packagemanifest $name -n $NS -o yaml >> ${NAMESPACE_PATH}/${NS}/packagemanifests
    echo '---------------' >> ${NAMESPACE_PATH}/${NS}/packagemanifests
done

for name in $(oc get subscriptions -n $NS -o=custom-columns=NAME:.metadata.name --no-headers)
do
    oc get subscription $name -n $NS -o yaml >> ${NAMESPACE_PATH}/${NS}/subscriptions
    echo '---------------' >> ${NAMESPACE_PATH}/${NS}/subscriptions
done

for name in $(oc get installplan -n $NS -o=custom-columns=NAME:.metadata.name --no-headers)
do
    oc get installplan $name -n $NS -o yaml >> ${NAMESPACE_PATH}/${NS}/installplans
    echo '---------------' >> ${NAMESPACE_PATH}/${NS}/installplans
done
