#!/bin/bash -x

DIR_NAME=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${DIR_NAME}/common.sh"
check_command

namespaces=()
# KubeVirt HCO related namespaces
namespaces+=("${INSTALLATION_NAMESPACE}" openshift-operator-lifecycle-manager openshift-marketplace)

# KubeVirt network related namespaces
namespaces+=(openshift-sdn)

# Golden images namesapce
namespaces+=(openshift-virtualization-os-images)

# CDI
resources+=(cdi)

# Run the collection of namespaces using must-gather
echo "${namespaces[@]}" | tr ' ' '\n' | xargs -t -I{} -P "${PROS}" --max-args=1 sh -c 'echo inspecting namespace $1 && oc adm inspect --dest-dir "${BASE_COLLECTION_PATH}" namespace $1' -- {}
