#!/bin/bash

IFS=$'\n'

BASE_COLLECTION_PATH="/must-gather"
NODES_PATH=${BASE_COLLECTION_PATH}/nodes/
mkdir -p ${NODES_PATH}
CRD_MANIFEST="/etc/node-gather-crd.yaml"
DAEMONSET_MANIFEST="/etc/node-gather-ds.yaml"

oc login -u system:admin
oc create -f $CRD_MANIFEST
oc adm policy add-scc-to-user privileged -n node-gather -z node-gather
oc create -f $DAEMONSET_MANIFEST

while true
do
    line=$(oc get ds node-gather-daemonset -o=custom-columns=DESIRED:.status.desiredNumberScheduled,READY:.status.numberReady --no-headers -n node-gather)

    DESIRED=$(echo $line | awk -F ' ' '{print $1}')
    READY=$(echo $line | awk -F ' ' '{print $2}')    
    if [[ $READY -eq $DESIRED ]]
    then
       break 
    fi
    sleep 1
done

for line in $(oc get pod -o=custom-columns=NODE:.spec.nodeName,NAME:.metadata.name --no-headers -n node-gather)
do
    node=$(echo $line | awk -F ' ' '{print $1}')
    pod=$(echo $line | awk -F ' ' '{print $2}')
    NODE_PATH=${NODES_PATH}/$node/
    mkdir -p ${NODE_PATH}
    oc exec -it $pod -n node-gather -- ip a >> $NODE_PATH/ip.txt
    oc exec -it $pod -n node-gather -- ip -o link show type bridge >> $NODE_PATH/bridge
    oc exec -it $pod -n node-gather -- bridge -j vlan show >> $NODE_PATH/vlan

    for i in $(oc exec -it $pod -n node-gather -- nft list tables );
    do
        family=`echo $i | awk -F ' ' '{print $2}' | sed 's/\r//'`
        table=`echo $i | awk -F ' ' '{print $3}' | sed 's/\r//'`
        oc exec -it $pod -n node-gather -- nft list table $family $table > "$NODE_PATH/nft-${family}-${table}"
    done

    for i in $(oc exec -it $pod -n node-gather -- ls /host/sys/bus/pci/devices/);
    do
        if [ $(oc exec -it $pod -n node-gather -- test -e /host/sys/bus/pci/devices/$i/sriov_numvfs && echo 1 || echo 0) -eq 1 ];
        then
            echo "sriov_numvfs on dev $i: $(oc exec -it $pod -n node-gather -- cat /host/sys/bus/pci/devices/$i/sriov_numvfs)"  >> $NODE_PATH/sys_sriov_numvfs
        fi
        if [ $(oc exec -it $pod -n node-gather -- test -e /host/sys/bus/pci/devices/$i/sriov_totalvfs && echo 1 || echo 0) -eq 1 ];
        then
            echo "sriov_numvfs on dev $i: $(oc exec -it $pod -n node-gather -- cat /host/sys/bus/pci/devices/$i/sriov_totalvfs)"  >> $NODE_PATH/sys_sriov_totalvfs
        fi
    done

    oc exec -it $pod -n node-gather -- ls -al /host/dev/vfio/ >> $NODE_PATH/dev_vfio
    oc exec -it $pod -n node-gather -- dmesg >> $NODE_PATH/dmesg
    oc exec -it $pod -n node-gather -- cat /host/proc/cmdline >> $NODE_PATH/proc_cmdline
    oc exec -it $pod -n node-gather -- lspci -vv >> $NODE_PATH/lspci
    oc exec -it $pod -n node-gather -- cat /host/etc/pcidp/config.json >> $NODE_PATH/pcidp_config.json
done

# Collect journal logs for specified units for all nodes
NODE_UNITS=(NetworkManager kubelet)
for NODE in $(oc get nodes --no-headers -o custom-columns=':metadata.name'); do
    NODE_PATH=${NODES_PATH}/$NODE/
    mkdir -p ${NODE_PATH}
    for UNIT in ${NODE_UNITS[@]}; do
        oc adm node-logs $NODE -u $UNIT > ${NODE_PATH}/${NODE}_logs_$UNIT &
    done
done

oc delete -f $DAEMONSET_MANIFEST
oc delete -f $CRD_MANIFEST
