#!/bin/bash

# Resource List
resources=()

for i in $(/usr/bin/oc get vm --all-namespaces --no-headers | awk '{print $1}')
do
  resources+=(ns/$i)
done

# Run the Collection of Resources using must-gather
for resource in ${resources[@]}; do
  /usr/bin/openshift-must-gather inspect ${resource}
done

exit 0
