#!/bin/bash
BASE_COLLECTION_PATH="/must-gather"

for i in $(/usr/bin/oc get pod --all-namespaces -l kubevirt.io=virt-launcher --no-headers | awk '{print $1 "_" $2}')
do
  ocproject=$(echo $i | awk -F_ '{print $1}')
  ocvm=$(echo $i | awk -F_ '{print $2}')
  vm_collection_path=${BASE_COLLECTION_PATH}/namespaces/${ocproject}/vm_definition
  
  mkdir -p ${vm_collection_path}
  
  /usr/bin/oc exec ${ocvm} -n ${ocproject} -c compute -- virsh dumpxml ${ocproject}_$(echo ${ocvm} | cut -d'-' -f3- | sed "s/-[^-]*$//") > ${vm_collection_path}/${ocvm}.vm.xml
done

exit 0
