#!/bin/bash

# Resource list
resources=()

# CNV HCO related namespaces
resources+=(ns/kubevirt-hyperconverged ns/openshift-operator-lifecycle-manager)

# CNV network related namespaces
resources+=(ns/kubemacpool-system ns/linux-bridge ns/openshift-sdn ns/cluster-network-addons-operator)

# CNV Web UI namespaces
resources+=(ns/kubevirt-web-ui)

# VM
resources+=(virtualmachines)

# VMI
resources+=(virtualmachineinstances virtualmachineinstancereplicasets virtualmachineinstancepresets virtualmachineinstancemigrations)

# v2v
resources+=(v2vvmwares)

resources+=(Network-attachment-definitions)

resources+=(networkaddonsconfig)

# Run the collection of resources using must-gather
for resource in ${resources[@]}; do
  /usr/bin/openshift-must-gather inspect --all-namespaces ${resource}
done

# Collect the CRDs
/usr/bin/gather_cnv_crds

# Collect namespaces that contains VMs
/usr/bin/gather_cnv_vms_namespaces

# Collect VMs details
/usr/bin/gather_cnv_vms_details

# Collect SSP details
/usr/bin/gather_cnv_ssp

# Collect network details
/usr/bin/gather_cnv_network

# Collect nodes details
/usr/bin/gather_cnv_nodes

exit 0
