#!/bin/bash

IFS=$'\n'

BASE_COLLECTION_PATH="/must-gather"
NODES_PATH=${BASE_COLLECTION_PATH}/nodes/
mkdir -p ${NODES_PATH}
CRD_MANIFEST="/etc/node-gather-crd.yaml"
DAEMONSET_MANIFEST="/etc/node-gather-ds.yaml"

oc login -u system:admin
oc create -f $CRD_MANIFEST
oc adm policy add-scc-to-user privileged -n node-gather -z node-gather
oc create -f $DAEMONSET_MANIFEST

while true
do
    line=$(oc get ds node-gather-daemonset -o=custom-columns=DESIRED:.status.desiredNumberScheduled,READY:.status.numberReady --no-headers -n node-gather)

    DESIRED=$(echo $line | awk -F ' ' '{print $1}')
    READY=$(echo $line | awk -F ' ' '{print $2}')    
    if [[ $READY -eq $DESIRED ]]
    then
       break 
    fi
    sleep 1
done

for line in $(oc get pod -o=custom-columns=NODE:.spec.nodeName,NAME:.metadata.name --no-headers -n node-gather)
do
    node=$(echo $line | awk -F ' ' '{print $1}')
    pod=$(echo $line | awk -F ' ' '{print $2}')
    NODE_PATH=${NODES_PATH}/$node/
    mkdir -p ${NODE_PATH}
    oc exec -it $pod -n node-gather -- ip a >> $NODE_PATH/ip.txt
    oc exec -it $pod -n node-gather -- brctl show >> $NODE_PATH/bridge
done

oc delete -f $DAEMONSET_MANIFEST
oc delete -f $CRD_MANIFEST
