#!/bin/bash

# Resource List
resources=()

# CNV HCO related namespaces
resources+=(ns/kubevirt-hyperconverged ns/openshift-operator-lifecycle-manager)

# CNV network related namespaces
resources+=(ns/kubemacpool-system ns/linux-bridge ns/openshift-sdn ns/cluster-network-addons-operator)

# CNV Web UI namespaces
resources+=(ns/kubevirt-web-ui)

# VM
resources+=(virtualmachines)

# VMI
resources+=(virtualmachineinstances virtualmachineinstancereplicasets virtualmachineinstancepresets virtualmachineinstancemigrations)

# v2v
resources+=(v2vvmwares)

# Run the Collection of Resources using must-gather
for resource in ${resources[@]}; do
  /usr/bin/openshift-must-gather inspect --all-namespaces ${resource}
done

# Collect namespaces that contains VMs
/usr/bin/gather-cnv-vm-namespaces

# Collect VMs definition
/usr/bin/gather-cnv-vm-definition

exit 0