---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
  name: node-gather
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-gather
  namespace: node-gather

