---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-gather-daemonset
  namespace: node-gather
  labels:
spec:
  selector:
    matchLabels:
      name: node-gather-daemonset
  template:
    metadata:
      labels:
        name: node-gather-daemonset      
    spec:
      serviceaccount: node-gather
      serviceAccountName: node-gather
      terminationGracePeriodSeconds: 0
      hostNetwork: true
      containers:
      - name: node-probe
        image: quay.io/mmirecki/cnv-node-gather
        command: ["/bin/bash", "-c", "echo ok > /tmp/healthy && sleep INF"]
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        readinessProbe:
          exec:
            command:
              - cat
              - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5

