---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm-ns__NS__-vm##VM##
  namespace: ns__NS__
spec:
  dataVolumeTemplates:
  - metadata:
      name: testdv__NS__##VM##
    spec:
      source:
        blank: {}
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
            - name: test-dv-vol__NS__##VM##
              volumeName: test-dv-vol__NS__##VM##
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
        - name: test-dv-vol__NS__##VM##
          dataVolume:
            name: testdv__NS__##VM##
